# Generated by Django 4.1.7 on 2023-03-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jamboard',
            name='author',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jamboard',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
