# Generated by Django 4.1.7 on 2023-03-11 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jamboard', '0002_jamboard_author_alter_jamboard_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('jamboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='jamboard.jamboard')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('jamboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='jamboard.jamboard')),
            ],
        ),
        migrations.RemoveField(
            model_name='images',
            name='jamboard',
        ),
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
