# Generated by Django 4.1.6 on 2023-02-10 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='authon',
            new_name='author',
        ),
    ]
