# Generated by Django 4.1.6 on 2023-02-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_description_alter_project_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.CharField(max_length=100),
        ),
    ]
